<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <RootNamespace>ICSharpCode.ILSpy.Deobfuscation.Tests</RootNamespace>

    <GenerateTestingPlatformEntryPoint>true</GenerateTestingPlatformEntryPoint>
    <StartupObject>ICSharpCode.ILSpy.Deobfuscation.Tests.MicrosoftTestingPlatformEntryPoint</StartupObject>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <PropertyGroup>
	<RestoreLockedMode>false</RestoreLockedMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="Microsoft.Testing.Extensions.VSTestBridge" />
    <PackageReference Include="AwesomeAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ILSpy.Deobfuscation\ILSpy.Deobfuscation.csproj" />
  </ItemGroup>

</Project>
